### ISSUE TITLE
Samenbestellungen für Webseite

### ISSUE THREAD

**Issue by RualSepp** [Edenhauser-IT/Schnittstellen#1]
### Bestellung

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| bestellnummer          | Integer | Fortlaufende Nummer der Bestellung                                                                                   |
| gesamtPreis            | String  | Preis   mit Komma als Dezimalzeichen                                                                                 |
| lfbis                  | String  | LFBIS   Nummer                                                                                                       |
| anmerkung              | String  | Anmerkung   vom Kunden                                                                                               |
| tierarzt               | Objekt  | Daten   des Ausgewählten Tierarztes mit gleichen Feldern, wie bei den Tierärzten   übermittelt wird.                 |
| rechnungsinformationen | Objekt  | Bei   der Bestellung eingetragene Rechnungsinformationen                                                             |
| artikel                | Array   | Array von bestellten Artikel Die Artikel kann ich auch in Agrarartikel und Samen aufteilen, wenn das   besser passt. |

**Comment by RualSepp** [comment]
### Rechnungsinformationen

| Bezeichnung | Datentyp | Beschreibung                      |
|-------------|----------|-----------------------------------|
| anrede      | String   | Anrede   ("Herr" oder "Frau")     |
| titel       | String   | Titel                             |
| vorname     | String   | Vorname                           |
| nachname    | String   | Nachname                          |
| email       | String   | E-Mail   Adresse                  |
| telefon     | String   | Telefonnummer                     |
| firma       | String   | Firma                             |
| uid         | String   | UID   der Firma, falls ausgefüllt |
| adresse     | String   | Straße   und Hausnummer           |
| plz         | String   | Postleitzahl                      |
| ort         | String   | Stadt/Ort                         |
| land        | String   | Land   ("Österreich")             |

**Comment by RualSepp** [comment]
### Artikel

| Bezeichnung   | Datentyp | Beschreibung                                                                                           |
|---------------|----------|--------------------------------------------------------------------------------------------------------|
| artikelnummer | String   | Bei Agrarartikeln: eindeutige Nummer/Text, des Artikel<br/>Bei Bullensamen: HB-Nummer                   |
| titel         | String   | Bei Agrarartikeln: Bezeichnung des Artikels<br/>Bei Bullensamen: Name Des Bullen                           |
| art           | String   | Bei Agrarartikeln: leer<br/>Bei Bullensamen: Behandlungsart der Samen ("normal",   "gesext", "spermvital") |
| preis         | String   | Preis   pro Stück                                                                                      |
| stueck        | String   | bestellte   Stückzahl                                                                                  |

**Comment by RualSepp** [comment]
### Beispiel

```json
{
    "bestellnummer": "5",
    "gesamtPreis": "10,5",
    "lfbis": "1234567",
    "anmerkung": "Wenn möglich sollte die Zustellung innerhalb der nächsten 2 Wochen erfolgen.",
    "tierarzt": {
        "titel": null,
        "vorname": "Gabriel",
        "nachname": "Winkler",
        "adresse": "Feldgasse 7",
        "ort": "6330 Kufstein",
        "handy": "0664/1515733",
        "email": "[gabriel.winkler@wtnw.at](mailto:gabriel.winkler@wtnw.at)",
        "telefon": "05372/62928",
        "besamerNummer": "7909923/1"
    },
    "rechnungsinformationen": {
        "anrede": "Herr",
        "titel": "",
        "vorname": "Max",
        "nachname": "Mustermann",
        "email": "[rinderzucht@lk-tirol.at](mailto:rinderzucht@lk-tirol.at)",
        "telefon": "+43 59292 1830",
        "firma": "Rinderzucht Tirol eGen",
        "uid": "",
        "adresse": "Brixner Straße 1",
        "plz": "6020",
        "ort": "Innsbruck",
        "land": "Österreich"
    },
    "artikel": [
        {
            "artikelnummer": "18",
            "titel": "Hinweistafel \"Mutterkühe schützen ihr Kälber!\"",
            "art": "",
            "preis": "3,5",
            "stueck": "3"
        }
    ]
}
```

**Comment by RualSepp** [comment]
Ich werde sowohl bei Tierarzt als auch bei den Infos 3 Felder für die Kommunikation verwenden:

1. EMail
2. Handy
3. Telefon

**Comment by RualSepp** [comment]
Was soll die Funktion zurückgeben?

**Comment by Leif2531** [comment]
Die Funktion kann einfach einen Boolean zurückgeben, ob die Übertragung funktioniert hat.
Außer es gibt noch Daten, die für die Webseite relevant sind.

**Comment by RualSepp** [comment]
Welche Daten?

**Comment by Leif2531** [comment]
Das war eher als Frage gemeint. Falls z.B. auf deiner Seite eine Validierung der Daten stattfindet, sollte das zurückgegeben werden.

**Comment by RualSepp** [comment]
Die Schnittstelle ist jetzt unter /website/addBestellung mit Parameter "data" verfügbar und gibt einen boolean Wert zurück

**Comment by RualSepp** [comment]
DB-ID bei Tierärzten mitschicken (bei Abfrage und Eingabe)

**Comment by RualSepp** [comment]
Benutzer-ID (von SSO bei Eingabe)

**Comment by RualSepp** [comment]
ID von Tierärzten wird jetzt mitgeschickt

**Comment by RualSepp** [comment]
Gibt es Probleme beim Zugriff?

Ich habe noch keinen zusätzlichen Eintrag erhalten.

**Comment by Leif2531** [comment]
Ich habe jetzt nochmal versucht eine Bestellung mit den Daten in dem GET Parameter "data" abzuschicken, das hat aber nicht funktioniert.

**Comment by RualSepp** [comment]
Welche Daten host do verwendet?

I hob folgenden Fehler bekommen:

ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String

**Comment by RualSepp** [comment]
Schaut so aus, als ob du bei der Bestellnummer keine String, sondern einen Integer mitgegeben hast.

Da weicht dein Beispiel von der Beschreibung ab.

Das kann ich auch auf meiner Seite ändern, wenn das für dich einfacher ist.

**Comment by Leif2531** [comment]
Ja, ich hatte da wohl einen Fehler in meiner Beschreibung.
Die Bestellnummer ist ein Integer.

**Comment by RualSepp** [comment]
Ist auf Integer umgestellt

**Comment by RualSepp** [comment]
Bitte nochmals probieren

**Comment by RualSepp** [comment]
Schickst du beim Tierarzt jetzt die ID mit?

I hob gerade an DB-Fehler wegen einem Mehrfachen Eintrag bei der besamerNummer bekommen.

**Comment by RualSepp** [comment]
![image](https://user-images.githubusercontent.com/75534122/170994483-e0997758-6462-48b8-b3b4-0aa3027e431a.png)

Der löst den Fehler aus

**Comment by Leif2531** [comment]
Ja, ich schicke beim Tierarzt die ID mit.
Die Tierarztdaten schicke ich aktuell genau so wieder zurück, wie ich sie bekomme.

**Comment by RualSepp** [comment]
Kannst du einen Test-Datensatz mit den Ausgabestelle schicken, damit ich die Schnittstelle anpassen kann?

**Comment by RualSepp** [comment]
Bei mir heißt das Feld "samenAusgabeOrt"

**Comment by RualSepp** [comment]
**Zu deinen Fragen:**

Versand von Artikeln ist möglich.

Bei Bestellung über den Tierarzt wird dieser die Samen zum Betrieb mitnehmen.

Es ist also möglich, dass die Samen über den Tierarzt laufen, die Artikel aber abgeholt / versandt werden.

**Comment by Leif2531** [comment]
Ich habe eine Testbestellung abgeschickt, aber nur "internal server error" zurück bekommen. 
Falls ich da noch etwas ändern soll kannst du dich einfach bei mir melden.

Hier sind auch noch die Daten, die ich abgeschickt habe:

```json
 {
  "bestellnummer": 26,
  "gesamtPreis": "211,50",
  "anmerkung": "TEST Bestellung von MICROLAB - Bestellung nicht bearbeiten",
  "lfbis": "8888888",
  "versand": true,
  "tierarzt": null,
  "samenAusgabeOrt": {
   "id": 843078,
   "name": "Samendepot Lienz"
  },
  "rechnungsinformationen": {
   "anrede": "Herr",
   "titel": null,
   "vorname": "Wolfgang",
   "nachname": "Aichberger",
   "email": "aw@microlab.at",
   "telefon": "0123456789",
   "handy": null,
   "firma": null,
   "uid": null,
   "adresse": "Straße 1",
   "plz": "1234",
   "ort": "Ort",
   "land": "Österreich"
  },
  "lieferinformationen": {
   "anrede": "Herr",
   "titel": null,
   "vorname": "Max",
   "nachname": "Mustermann",
   "email": null,
   "telefon": null,
   "handy": null,
   "firma": "MICROLAB",
   "adresse": "Hannesgrub Süd 6",
   "plz": "4911",
   "ort": "Tumeltsham/ Ried im Innkreis",
   "land": "Österreich"
  },
  "artikel": [
   {
    "artikelnummer": "ART_BIPILL",
    "titel": "Bi-PILL. Die erste Bicarbonat-Pille.",
    "art": "",
    "preis": "20,50",
    "stueck": "1"
   },
   {
    "artikelnummer": "ART_ÜZ",
    "titel": "Überzüge",
    "art": "",
    "preis": "4,00",
    "stueck": "1"
   },
   {
    "artikelnummer": "ART_HASU",
    "titel": "Handschuhe Supersensitivity",
    "art": "",
    "preis": "10,00",
    "stueck": "5"
   },
   {
    "artikelnummer": "ART_MS",
    "titel": "Messstab",
    "art": "",
    "preis": "7,00",
    "stueck": "1"
   },
   {
    "artikelnummer": "AT365816738",
    "titel": "ANDREW, konventionell",
    "art": "konventionell",
    "preis": "13,00",
    "stueck": "1"
   },
   {
    "artikelnummer": "DK2371402974",
    "titel": "BONFIRE, gesext",
    "art": "gesext",
    "preis": "39,00",
    "stueck": "3"
   }
  ]
 }
```

**Comment by RualSepp** [comment]
Sollte jetzt funktionieren.
