### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by RualSepp** [Edenhauser-IT/Schnittstellen#3]
URLs für Login / Registrierung angeben

**Comment by RualSepp** [comment]
### LOGIN: /website/userLogin

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| code | String | SMS-Code (bei 1. Login)
| name| String| Benutzername                                                                                   |
| passwort| String | Passwort                                                                               |
| info| String  | Zusatz-Informationen (z.B. IP-Adresse)                                                                                                      |

### Rückgabewerte:

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| benutzerId| Integer | DB-ID des Benutzers |
| token | String | Token für Auth-Header |
| expires | String  | Ablaufdatum des Token                                                                                                    |
| errors | String [] | Fehler  (z.B. falsches Passwort)                                                                                                    |

**Comment by RualSepp** [comment]
### SIGNUP: /website/userSignup

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| name| String| Benutzername                                                                                   |
| passwort| String | Passwort                                                                               |
| lfbis| String  | Betriebsnummer                                                                                                     |
| handy | String | Handynummer des Betriebes |
| email | String | E-Mail Adresse des Betriebes |
| info | String | Zusatz-Informationen (z.B. IP-Adresse) |

### Rückgabewerte:

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| code | String | Freischaltcode des Benutzers |
| name | String | Benutzername |
| passwort | String  | Passwort                                                                                                    |
| lfbis | String | Betriebsnummer |
| hand | String | Handynummer des Betriebes |
| email | String | E-Mail Adresse des Betriebes |
| info | String | Zusatz-Informationen (z.B. IP-Adresse) |
| errors | String [] | Fehler  (z.B. falsches Passwort)                                                                                                    |

**Comment by RualSepp** [comment]
### SEND PASSWORD: /website/userSendPassword

Dem Benutzer (falls registriert) wird sein Passwort auf die hinterlegte E-Mail Adresse geschickt.

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| name| String| Benutzername                                                                                   |

### Rückgabewerte:

| Bezeichnung            | Datentyp | Beschreibung                                                                                                         |
|------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
| Error | String | Fehler beim Senden (NULL bei Erfolg) |

**Comment by Leif2531** [comment]
Gibt es eine Möglichkeit, wie ich die Registrierung testen kann?
Z.B eine bestimmte LFBIS Nummer und E-Mail.

**Comment by RualSepp** [comment]
Ich habe jetzt einen Testbetrieb für dich angelegt:

LFBIS: 8888888
Vorname: Testvorname
Nachname: Testnachname
Hofname: Testhofname

E-Mail: entwicklung@edenhauser.it
Handy: 0664/1166881

**Comment by Leif2531** [comment]
Wie soll die Bestätigung der Handynummer funktionieren?
Also was ist die URL und welche Daten müssen übermittelt werden?

**Comment by RualSepp** [comment]
Du bekommst von mir den Code mitgeschickt und der Benutzer bekommt ihn per SMS.

Dann gibt er den Code bei dir ein.

Danach schickst du Code, Benutzername und Passwort an /website/userLogin.

**Comment by RualSepp** [comment]
2x Code erhalten: 470 079, 710 182

**Comment by RualSepp** [comment]
mit /website/deleteMicrolabUser werden alle Benutzer deren Benutzername mit "MICROLAB" anfängt, gelöscht.

**Comment by RualSepp** [comment]
Ich könnte zum Testen auch deine Handynummer eintragen

**Comment by Leif2531** [comment]
Ich bekomme den Code zwar sowieso über die Schnittstelle beim Signup, aber meine Handynummer ist: +43 676 7949864

**Comment by Leif2531** [comment]
Beim Login bekomme ich immer den Fehler "Gerät nicht freigeschaltet". Muss ich da noch etwas ändern?

**Comment by RualSepp** [comment]
Nein, das bezieht sich auf Handies, ist angepasst und sollte jetzt gehen.

**Comment by Leif2531** [comment]
Der Login funktioniert jetzt, aber beim Passwort zusenden bekomme ich immer den Fehler "Benutzername existiert nicht!", auch wenn ich mich mit dem selben Benutzernamen (MICROLAB) einloggen kann und bei der Registrierung die Meldung "Benutzername existiert bereits!" bekomme.

**Comment by RualSepp** [comment]
I hob etz an Parameternamen auf: "name" geändert.

**Comment by RualSepp** [comment]
Hat funktioniert, soll ich deine E-Mail Adresse eintragen?

**Comment by Leif2531** [comment]
OK, mein Mail Adresse ist aw@microlab.at

**Comment by Leif2531** [comment]
Die Abfragen der Schnittstelle sollen, wenn möglich, noch auf POST umgestellt werden, damit die Passwörter beim login und signup nicht unverschlüsselt übertragen werden.

**Comment by RualSepp** [comment]
ok, also signup und login?

**Comment by Leif2531** [comment]
Ich würde die Anderen auch umstellen, aber wichtig sind in erster Linie signup und login, weil bei denen Passwörter übertragen werden.

**Comment by RualSepp** [comment]
Willst du die Werte im Header mitgeben?

**Comment by Leif2531** [comment]
den Header würde ich lassen

**Comment by RualSepp** [comment]
ok, folgende Methoden sind jetzt POST:

login, userLogin, userSignup, userSendPassword, addBestellung

**Comment by RualSepp** [comment]
Ich würde beim Aufruf der Webseite vom RZApp aus einen Parameter "RZApp_Auth" im Header mitgeben.

Über  /website/userTokenLogin (1 String Parameter mit dem Token) kann der Benutzer dann eingeloggt werden.

Das Ergebnis ist gleich wie beim Benutzername/Passwort Login.

**Comment by Leif2531** [comment]
Hier sind die Daten die ich, wie besprochen, noch bei Login, TokenLogin und Signup brauche:

- Anrede
- Titel
- Vorname
- Nachname
- E-Mail
- Handy- oder Telefonnummer
- LFBIS
- Adresse
- PLZ
- Ort
- Benutzername

**Comment by RualSepp** [comment]
Ich schicke jetzt eine Liste der Betriebe ( deine Datenfelder ) mit, die diesem Benutzer zugeordnet sind.
