### ISSUE TITLE
Link für Samenbestellungen

### ISSUE THREAD

**Issue by RualSepp** [Edenhauser-IT/Schnittstellen#5]
Ich bräuchte einen Link, wo ich den Token mitgebe, für den Einstieg in die Webseite vom RZApp aus.

Damit braucht sich der Benutzer auf der Webseite nicht mehr einloggen.

**Comment by RualSepp** [comment]
Wenn ich eine Ohrmarken-Nummer als Parameter mitgebe sollte der Benutzer (eingeloggt) auf die Seite des Stieres weitergeleitet werden.

**Comment by RualSepp** [comment]
Ich gebe jetzt bei JEDEM Aufruf den Header "RZApp_Auth" mit dem Token mit.

Damit gräuchte ich jetzt nur noch die URL für den Aufruf der Stiere mit der Ohrmarken-Nummer.

**Comment by Leif2531** [comment]
Das Thema ist bei mir für nächste Woche geplant. Ich melde mich dann bei dir.

**Comment by Leif2531** [comment]
Wenn man über GET oder POST den Parameter "bullLink" mit der Ohrmarken-Nummer im übergibt wird man jetzt auf den jeweiligen Bullen weitergeleitet.
Du kannst als Link also z.B. https://www.rinderzucht.tirol/index.html?bullLink=DE0955642886 verwenden.

Der automatische login über den Token im Header sollte jetzt auch funktionieren.

**Comment by RualSepp** [comment]
Kann ich auch abfragen, ob die Ohrmarken-Nummer existiert?

Offensichtlich ist das nicht bei allen Anpaarungsvorschlägen der Fall (z.B. Music  DE0540816136)

**Comment by RualSepp** [comment]
Ich lade jetzt die Seite im Hintergrund, und schaue, ob "easybulls__detail" vorkommt.

Das ist aber weder schön, noch schnell. Vielleicht gibt es eine bessere Lösung.

**Comment by Leif2531** [comment]
Über die URL https://www.rinderzucht.tirol/sites/www.rinderzucht.tirol/bull.php bekommst du jetzt den Link zum angegeben Bullen.

Z.B.: https://www.rinderzucht.tirol/sites/www.rinderzucht.tirol/bull.php?bullLink=DE0955642886

**Comment by RualSepp** [comment]
Link funktioniert einwandfrei.

Leider funktioniert des Login von deiner Seite noch nicht, beim Backend wird der Token nicht angefragt.

Er wird bei mir mit dem Header "RZApp_Auth" mitgegeben.

**Comment by RualSepp** [comment]
Die Token - Schnittstelle wurde bis jetzt NIE verwendet, siehst du das auch so?

**Comment by Leif2531** [comment]
website/userTokenLogin habe ich beim Testen auf jeden Fall aufgerufen.

Versuch den Login bitte noch einmal, damit ich mir die Daten im Log ansehen kann.

**Comment by RualSepp** [comment]
![image](https://user-images.githubusercontent.com/75534122/189681737-e3669eea-0b17-411f-90d8-8df66a445ffe.png)

Ok, heute sind Logins drinnen.

**Comment by RualSepp** [comment]
Jetzt hob i amoi an Link für a Samenbestellung aufgerufen.

**Comment by RualSepp** [comment]
Beim Backend kommt da kein Aufruf.

**Comment by Leif2531** [comment]
Kannst beim Header "RZApp-Auth" versuchen?
Also mit "-" statt "_".

**Comment by RualSepp** [comment]
Habe ich jetzt probiert, kein anderes Verhalten, im Log kein Aufruf beim Backend.

**Comment by RualSepp** [comment]
I gib etz den Token als Parameter mit, schaut amoi gut aus, auf der Webseite steht oben "LOGOUT".
