### ISSUE TITLE
Samenbestellung über URL

### ISSUE THREAD

**Issue by RualSepp** [Edenhauser-IT/Schnittstellen#6]
Manchmal kommt man nicht direkt auf die Seite des Stieres, sondern auf die Seite mit allen Stieren.

Woran könnte das liegen?

**Comment by RualSepp** [comment]
Von mir wird dabei exakt dieselbe URL aufgerufen, z.B. 

https://www.rinderzucht.tirol/besamung/holstein-27.html?id=130642&contentId=896&type=easybull&RZApp_Auth=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJSWlMtU0VSVkVSIiwic3ViIjoiam9zZWYuZWRlbmhhdXNlciIsImF1dGhvcml0aWVzIjpbIlVTRVIiLCJBRE1JTiIsIkRFVkVMT1BFUiJdLCJpYXQiOjE2NjQzNTU1OTAsImV4cCI6MTk3OTk3NDc5MH0.UEH-CWi-YQAnMPV

Beim 1. mal wurde die allgemeine, beim 2. mal die Seite des Stieres geöffnet.

**Comment by Leif2531** [comment]
Ich hatte einen Fehler, durch den die Parameter beim Login über den Token verloren gingen. Damit ist man beim ersten Aufruf zur Stierliste gekommen.

Jetzt sollte man aber direkt auf die Seite des Stieres kommen.
